//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace maf {

public class AlternativeLocation : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal AlternativeLocation(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AlternativeLocation obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(AlternativeLocation obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~AlternativeLocation() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          mafPINVOKE.delete_AlternativeLocation(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string mimeType {
    set {
      mafPINVOKE.AlternativeLocation_mimeType_set(swigCPtr, value);
      if (mafPINVOKE.SWIGPendingException.Pending) throw mafPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = mafPINVOKE.AlternativeLocation_mimeType_get(swigCPtr);
      if (mafPINVOKE.SWIGPendingException.Pending) throw mafPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public TrackArray tracks {
    set {
      mafPINVOKE.AlternativeLocation_tracks_set(swigCPtr, TrackArray.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = mafPINVOKE.AlternativeLocation_tracks_get(swigCPtr);
      TrackArray ret = (cPtr == global::System.IntPtr.Zero) ? null : new TrackArray(cPtr, false);
      return ret;
    } 
  }

  public string uri {
    set {
      mafPINVOKE.AlternativeLocation_uri_set(swigCPtr, value);
      if (mafPINVOKE.SWIGPendingException.Pending) throw mafPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = mafPINVOKE.AlternativeLocation_uri_get(swigCPtr);
      if (mafPINVOKE.SWIGPendingException.Pending) throw mafPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public AlternativeLocation() : this(mafPINVOKE.new_AlternativeLocation(), true) {
  }

}

}
