//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace maf {

public enum AttributeType {
  ATTRIB_NORMAL,
  ATTRIB_POSITION,
  ATTRIB_COLOR,
  ATTRIB_TEXCOORD,
  ATTRIB_INDEX,
  ATTRIB_TANGENT,
  ATTRIB_WEIGHTS,
  ATTRIB_JOINTS,
  TEXTURE_RGB,
  TEXTURE_GBR_3PLANE_420_UNORM
}

}
