//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace maf {

public class BufferInfoHeaderArray : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<BufferInfoHeader>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal BufferInfoHeaderArray(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(BufferInfoHeaderArray obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(BufferInfoHeaderArray obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~BufferInfoHeaderArray() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          mafPINVOKE.delete_BufferInfoHeaderArray(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public BufferInfoHeaderArray(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (BufferInfoHeader element in c) {
      this.Add(element);
    }
  }

  public BufferInfoHeaderArray(global::System.Collections.Generic.IEnumerable<BufferInfoHeader> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (BufferInfoHeader element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public BufferInfoHeader this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < 0 || (uint)value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public bool IsEmpty {
    get {
      return empty();
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(BufferInfoHeader[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(BufferInfoHeader[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, BufferInfoHeader[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public BufferInfoHeader[] ToArray() {
    BufferInfoHeader[] array = new BufferInfoHeader[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<BufferInfoHeader> global::System.Collections.Generic.IEnumerable<BufferInfoHeader>.GetEnumerator() {
    return new BufferInfoHeaderArrayEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new BufferInfoHeaderArrayEnumerator(this);
  }

  public BufferInfoHeaderArrayEnumerator GetEnumerator() {
    return new BufferInfoHeaderArrayEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class BufferInfoHeaderArrayEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<BufferInfoHeader>
  {
    private BufferInfoHeaderArray collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public BufferInfoHeaderArrayEnumerator(BufferInfoHeaderArray collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public BufferInfoHeader Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (BufferInfoHeader)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public BufferInfoHeaderArray() : this(mafPINVOKE.new_BufferInfoHeaderArray__SWIG_0(), true) {
  }

  public BufferInfoHeaderArray(BufferInfoHeaderArray other) : this(mafPINVOKE.new_BufferInfoHeaderArray__SWIG_1(BufferInfoHeaderArray.getCPtr(other)), true) {
    if (mafPINVOKE.SWIGPendingException.Pending) throw mafPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Clear() {
    mafPINVOKE.BufferInfoHeaderArray_Clear(swigCPtr);
  }

  public void Add(BufferInfoHeader x) {
    mafPINVOKE.BufferInfoHeaderArray_Add(swigCPtr, BufferInfoHeader.getCPtr(x));
    if (mafPINVOKE.SWIGPendingException.Pending) throw mafPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = mafPINVOKE.BufferInfoHeaderArray_size(swigCPtr);
    return ret;
  }

  private bool empty() {
    bool ret = mafPINVOKE.BufferInfoHeaderArray_empty(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = mafPINVOKE.BufferInfoHeaderArray_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    mafPINVOKE.BufferInfoHeaderArray_reserve(swigCPtr, n);
  }

  public BufferInfoHeaderArray(int capacity) : this(mafPINVOKE.new_BufferInfoHeaderArray__SWIG_2(capacity), true) {
    if (mafPINVOKE.SWIGPendingException.Pending) throw mafPINVOKE.SWIGPendingException.Retrieve();
  }

  private BufferInfoHeader getitemcopy(int index) {
    BufferInfoHeader ret = new BufferInfoHeader(mafPINVOKE.BufferInfoHeaderArray_getitemcopy(swigCPtr, index), true);
    if (mafPINVOKE.SWIGPendingException.Pending) throw mafPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private BufferInfoHeader getitem(int index) {
    BufferInfoHeader ret = new BufferInfoHeader(mafPINVOKE.BufferInfoHeaderArray_getitem(swigCPtr, index), false);
    if (mafPINVOKE.SWIGPendingException.Pending) throw mafPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, BufferInfoHeader val) {
    mafPINVOKE.BufferInfoHeaderArray_setitem(swigCPtr, index, BufferInfoHeader.getCPtr(val));
    if (mafPINVOKE.SWIGPendingException.Pending) throw mafPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(BufferInfoHeaderArray values) {
    mafPINVOKE.BufferInfoHeaderArray_AddRange(swigCPtr, BufferInfoHeaderArray.getCPtr(values));
    if (mafPINVOKE.SWIGPendingException.Pending) throw mafPINVOKE.SWIGPendingException.Retrieve();
  }

  public BufferInfoHeaderArray GetRange(int index, int count) {
    global::System.IntPtr cPtr = mafPINVOKE.BufferInfoHeaderArray_GetRange(swigCPtr, index, count);
    BufferInfoHeaderArray ret = (cPtr == global::System.IntPtr.Zero) ? null : new BufferInfoHeaderArray(cPtr, true);
    if (mafPINVOKE.SWIGPendingException.Pending) throw mafPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, BufferInfoHeader x) {
    mafPINVOKE.BufferInfoHeaderArray_Insert(swigCPtr, index, BufferInfoHeader.getCPtr(x));
    if (mafPINVOKE.SWIGPendingException.Pending) throw mafPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, BufferInfoHeaderArray values) {
    mafPINVOKE.BufferInfoHeaderArray_InsertRange(swigCPtr, index, BufferInfoHeaderArray.getCPtr(values));
    if (mafPINVOKE.SWIGPendingException.Pending) throw mafPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    mafPINVOKE.BufferInfoHeaderArray_RemoveAt(swigCPtr, index);
    if (mafPINVOKE.SWIGPendingException.Pending) throw mafPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    mafPINVOKE.BufferInfoHeaderArray_RemoveRange(swigCPtr, index, count);
    if (mafPINVOKE.SWIGPendingException.Pending) throw mafPINVOKE.SWIGPendingException.Retrieve();
  }

  public static BufferInfoHeaderArray Repeat(BufferInfoHeader value, int count) {
    global::System.IntPtr cPtr = mafPINVOKE.BufferInfoHeaderArray_Repeat(BufferInfoHeader.getCPtr(value), count);
    BufferInfoHeaderArray ret = (cPtr == global::System.IntPtr.Zero) ? null : new BufferInfoHeaderArray(cPtr, true);
    if (mafPINVOKE.SWIGPendingException.Pending) throw mafPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    mafPINVOKE.BufferInfoHeaderArray_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    mafPINVOKE.BufferInfoHeaderArray_Reverse__SWIG_1(swigCPtr, index, count);
    if (mafPINVOKE.SWIGPendingException.Pending) throw mafPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, BufferInfoHeaderArray values) {
    mafPINVOKE.BufferInfoHeaderArray_SetRange(swigCPtr, index, BufferInfoHeaderArray.getCPtr(values));
    if (mafPINVOKE.SWIGPendingException.Pending) throw mafPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
