//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace maf {

public class Frame : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Frame(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Frame obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Frame obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Frame() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          mafPINVOKE.delete_Frame(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public byte index {
    set {
      mafPINVOKE.Frame_index_set(swigCPtr, value);
    } 
    get {
      byte ret = mafPINVOKE.Frame_index_get(swigCPtr);
      return ret;
    } 
  }

  public ulong timestamp {
    set {
      mafPINVOKE.Frame_timestamp_set(swigCPtr, value);
    } 
    get {
      ulong ret = mafPINVOKE.Frame_timestamp_get(swigCPtr);
      return ret;
    } 
  }

  public uint length {
    set {
      mafPINVOKE.Frame_length_set(swigCPtr, value);
    } 
    get {
      uint ret = mafPINVOKE.Frame_length_get(swigCPtr);
      return ret;
    } 
  }

  public global::System.IntPtr data {
    set {
      mafPINVOKE.Frame_data_set(swigCPtr, value);
    } 
    get {
      global::System.IntPtr ret = mafPINVOKE.Frame_data_get(swigCPtr);
      return ret;
    } 
  }

  public Frame(byte i, ulong t, uint byteLength, global::System.IntPtr buffer) : this(mafPINVOKE.new_Frame__SWIG_0(i, t, byteLength, buffer), true) {
  }

  public Frame(byte i, ulong t, uint byteLength) : this(mafPINVOKE.new_Frame__SWIG_1(i, t, byteLength), true) {
  }

  public Frame(byte i, ulong t) : this(mafPINVOKE.new_Frame__SWIG_2(i, t), true) {
  }

  public Frame(byte i) : this(mafPINVOKE.new_Frame__SWIG_3(i), true) {
  }

  public Frame() : this(mafPINVOKE.new_Frame__SWIG_4(), true) {
  }

}

}
