//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace maf {

public class maf {
  public static int componentSize(ComponentType ct) {
    int ret = mafPINVOKE.componentSize((int)ct);
    return ret;
  }

  public static int sampleSize(SampleType st) {
    int ret = mafPINVOKE.sampleSize((int)st);
    return ret;
  }

  public static ulong getTimestamp(double time_s) {
    ulong ret = mafPINVOKE.getTimestamp__SWIG_0(time_s);
    return ret;
  }

  public static ulong getTimestamp(long time_us) {
    ulong ret = mafPINVOKE.getTimestamp__SWIG_1(time_us);
    return ret;
  }

  public static double getTime_s(ulong timestamp) {
    double ret = mafPINVOKE.getTime_s(timestamp);
    return ret;
  }

}

}
