//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace maf {

public class OrthographicCameraViewingVolume : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal OrthographicCameraViewingVolume(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(OrthographicCameraViewingVolume obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(OrthographicCameraViewingVolume obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~OrthographicCameraViewingVolume() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          mafPINVOKE.delete_OrthographicCameraViewingVolume(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public double xmag {
    set {
      mafPINVOKE.OrthographicCameraViewingVolume_xmag_set(swigCPtr, value);
    } 
    get {
      double ret = mafPINVOKE.OrthographicCameraViewingVolume_xmag_get(swigCPtr);
      return ret;
    } 
  }

  public double ymag {
    set {
      mafPINVOKE.OrthographicCameraViewingVolume_ymag_set(swigCPtr, value);
    } 
    get {
      double ret = mafPINVOKE.OrthographicCameraViewingVolume_ymag_get(swigCPtr);
      return ret;
    } 
  }

  public OrthographicCameraViewingVolume() : this(mafPINVOKE.new_OrthographicCameraViewingVolume(), true) {
  }

}

}
