name: build check on pull request
run-name: ${{ github.actor }} triggered a build on unity cloud
on:
  pull_request:
    branches:
      - 'development'
      - 'main'
jobs:
  unity-cloud-build-win64:
    uses: ./.github/workflows/UnityCloudBuild.yml
    with:
      UnityCloudOrganisation: ${{ vars.UNITY_CLOUD_ORGANIZATION_ID }}
      UnityCloudProject: ${{ vars.UNITY_CLOUD_PROJECT_ID }}
      UnityCloudBuildTarget: rt-xr-player-win64
      DownloadBinaryToArtifact: true
      ReportShareUrl: false
    secrets:
      UnityCloudBuildApiKey: ${{ secrets.UNITY_CLOUD_BUILD_API_KEY }}
